#!/usr/bin/env bash
#
# compile.sh - runs inside the MSYS2 MINGW64 environment.
#
# Prepares the GKrellM headers, derives an import library from the installed
# gkrellm.exe, compiles the plugin and verifies the resulting DLL.
#
# Called by bootstrap.ps1, but it is perfectly usable on its own:
#
#   ./compile.sh --gkrellm-exe "/c/Program Files/GKrellM/gkrellm.exe" \
#                --source-tree ./work/gkrellm-2.5.1 \
#                --project . --out ./build
#
set -o errexit
set -o nounset
set -o pipefail

GKRELLM_EXE=""
SOURCE_TREE=""
PROJECT="."
OUT="./build"

log()  { printf '    %s\n' "$*"; }
ok()   { printf '    [ok] %s\n' "$*"; }
die()  { printf '\n[FAIL] %s\n' "$*" >&2; exit 1; }

while [ $# -gt 0 ]; do
	case "$1" in
		--gkrellm-exe) GKRELLM_EXE="$2"; shift 2 ;;
		--source-tree) SOURCE_TREE="$2"; shift 2 ;;
		--project)     PROJECT="$2";     shift 2 ;;
		--out)         OUT="$2";         shift 2 ;;
		*) die "unknown argument: $1" ;;
	esac
done

[ -n "$GKRELLM_EXE" ] || die "--gkrellm-exe is required"
[ -n "$SOURCE_TREE" ] || die "--source-tree is required"
[ -f "$GKRELLM_EXE" ] || die "gkrellm.exe not found at: $GKRELLM_EXE"
[ -d "$SOURCE_TREE" ] || die "GKrellM source tree not found at: $SOURCE_TREE"

INC="$OUT/include/gkrellm2"
LIB="$OUT/lib"
mkdir -p "$INC" "$LIB" "$OUT/obj"

# ---------------------------------------------------------------------------
echo
echo "--- Toolchain ---"
# ---------------------------------------------------------------------------
for tool in gcc pkg-config objdump dlltool; do
	command -v "$tool" >/dev/null 2>&1 || die "$tool is missing from the MINGW64 environment"
done
ok "gcc      $(gcc -dumpversion)"
ok "binutils $(objdump --version | head -1 | sed 's/.*) //')"

HOST_TRIPLE="$(gcc -dumpmachine)"
case "$HOST_TRIPLE" in
	x86_64-w64-mingw32) ok "target   $HOST_TRIPLE" ;;
	*) die "wrong toolchain: $HOST_TRIPLE (expected x86_64-w64-mingw32; are you in the MINGW64 shell?)" ;;
esac

pkg-config --exists gtk+-2.0 || die "GTK+ 2.0 development files not found (mingw-w64-x86_64-gtk2)"
ok "gtk+-2.0 $(pkg-config --modversion gtk+-2.0)"

# ---------------------------------------------------------------------------
echo
echo "--- GKrellM headers ---"
# ---------------------------------------------------------------------------
# Headers do not all live in src/: anything shared with the gkrellmd server
# sits in shared/. Locate each one instead of assuming a path, so this keeps
# working if upstream moves files around again.
find_header() {
	local name="$1" hit=""
	local d
	for d in "$SOURCE_TREE/src" "$SOURCE_TREE/shared" "$SOURCE_TREE"; do
		if [ -f "$d/$name" ]; then hit="$d/$name"; break; fi
	done
	if [ -z "$hit" ]; then
		hit="$(find "$SOURCE_TREE" -type f -name "$name" 2>/dev/null | head -1)"
	fi
	[ -n "$hit" ] || return 1
	cp -f "$hit" "$INC/$name"
	ok "$name  <- ${hit#"$SOURCE_TREE"/}"
	return 0
}

find_header gkrellm.h \
	|| die "gkrellm.h not found anywhere in the source tree"
find_header gkrellm-public-proto.h \
	|| die "gkrellm-public-proto.h not found anywhere in the source tree"
find_header log.h \
	|| die "log.h not found anywhere in the source tree"

# Present from 2.5.0 onwards. Older trees used a callback table instead of
# dllimport, which this plugin does not support.
find_header gkrellm-visibility.h \
	|| die "gkrellm-visibility.h missing: this source tree is older than 2.5.0"

# gkrellm-version.h is produced by the build system, so it may be absent from
# a plain tarball. Synthesise it from the directory name.
if ! find_header gkrellm-version.h; then
	VER="$(basename "$SOURCE_TREE" | sed 's/^gkrellm-//')"
	MAJ="$(echo "$VER" | cut -d. -f1)"
	MIN="$(echo "$VER" | cut -d. -f2)"
	REV="$(echo "$VER" | cut -d. -f3)"
	: "${MAJ:=2}" ; : "${MIN:=5}" ; : "${REV:=1}"
	cat > "$INC/gkrellm-version.h" <<EOF
/* Generated by compile.sh because the tarball ships no pre-built copy. */
#ifndef GKRELLM_VERSION_H
#define GKRELLM_VERSION_H
#define GKRELLM_VERSION_MAJOR $MAJ
#define GKRELLM_VERSION_MINOR $MIN
#define GKRELLM_VERSION_REV   $REV
#define GKRELLM_EXTRAVERSION  ""
#define GKRELLM_CHECK_VERSION(major,minor,rev) \\
	(GKRELLM_VERSION_MAJOR > (major) || \\
	(GKRELLM_VERSION_MAJOR == (major) && GKRELLM_VERSION_MINOR > (minor)) || \\
	(GKRELLM_VERSION_MAJOR == (major) && GKRELLM_VERSION_MINOR == (minor) && \\
	GKRELLM_VERSION_REV >= (rev)))
#endif
EOF
	ok "gkrellm-version.h (generated for $MAJ.$MIN.$REV)"
fi

# ---------------------------------------------------------------------------
echo
echo "--- Import library from gkrellm.exe ---"
# ---------------------------------------------------------------------------
# On Windows a plugin cannot resolve symbols from the host process the way
# dlopen() does on Unix. Since 2.5.0 gkrellm.exe exports its public API
# (GKRELLM_API expands to __declspec(dllexport)), so we can build a normal
# import library against the executable.

EXPORTS="$(objdump -p "$GKRELLM_EXE" | grep -oE '\bgkrellm_[A-Za-z0-9_]+' | sort -u || true)"
COUNT="$(printf '%s\n' "$EXPORTS" | grep -c . || true)"

if [ "$COUNT" -lt 50 ]; then
	echo
	echo "  gkrellm.exe exports only $COUNT gkrellm_* symbols."
	echo "  A plugin cannot be linked against this build."
	echo
	echo "  Most likely cause: the installed GKrellM is older than 2.5.0."
	echo "  Check Help -> About in GKrellM; version 2.5.0 or newer is required."
	die "gkrellm.exe does not export a usable plugin API"
fi
ok "$COUNT exported gkrellm_* symbols found"

{
	echo "LIBRARY gkrellm.exe"
	echo "EXPORTS"
	printf '%s\n' "$EXPORTS"
} > "$LIB/gkrellm.def"

dlltool --def "$LIB/gkrellm.def" \
	--dllname gkrellm.exe \
	--output-lib "$LIB/libgkrellm.a"
ok "libgkrellm.a generated"

# ---------------------------------------------------------------------------
echo
echo "--- Compiling ---"
# ---------------------------------------------------------------------------
CFLAGS="-O2 -Wall -Wextra -Wno-unused-parameter -std=gnu99"
CFLAGS="$CFLAGS -DWIN32 -D_WIN32_WINNT=0x0601"
CFLAGS="$CFLAGS -I$OUT/include $(pkg-config --cflags gtk+-2.0)"

# -static-libgcc matters: without it the DLL depends on libgcc_s_seh-1.dll,
# which is not present in the GKrellM installation directory, and the plugin
# would fail to load with no diagnostic at all.
LDFLAGS="-shared -static-libgcc -Wl,--enable-auto-image-base"
LDLIBS="$LIB/libgkrellm.a $(pkg-config --libs gtk+-2.0) -lkernel32 -luser32"

# Every vendor library (dxgi, pdh, atiadlxx, ze_loader) is reached through
# LoadLibrary/GetProcAddress, never an import.  That is deliberate: the
# dependency check further down would otherwise reject the DLL on any machine
# that does not happen to have all three vendor drivers installed.
SOURCES="gkrellm-gpu.c gpu-core.c gpu-adapter.c gpu-pdh.c gpu-nvidia.c gpu-amd.c gpu-intel.c"

log "gcc $CFLAGS"
OBJS=""
for src in $SOURCES; do
	obj="$OUT/obj/${src%.c}.o"
	gcc $CFLAGS -c "$PROJECT/src/$src" -o "$obj"
	OBJS="$OBJS $obj"
	ok "compiled $src"
done

gcc $LDFLAGS -o "$OUT/gkrellm-gpu.dll" $OBJS $LDLIBS
ok "linked"

# ---------------------------------------------------------------------------
echo
echo "--- Verifying the DLL ---"
# ---------------------------------------------------------------------------
ARCH="$(objdump -f "$OUT/gkrellm-gpu.dll" | grep '^architecture' || true)"
case "$ARCH" in
	*i386:x86-64*) ok "architecture x86-64" ;;
	*) die "unexpected architecture: $ARCH" ;;
esac

objdump -p "$OUT/gkrellm-gpu.dll" | grep -q "gkrellm_init_plugin" \
	|| die "gkrellm_init_plugin is not exported (check GKRELLM_EXPORT)"
ok "gkrellm_init_plugin is exported"

# Anything the plugin imports must already be loaded by gkrellm.exe, otherwise
# Windows silently refuses to load the plugin.
DEPS="$(objdump -p "$OUT/gkrellm-gpu.dll" | grep 'DLL Name:' | sed 's/.*DLL Name: //' | sort -u)"
GKRELLM_DIR="$(dirname "$GKRELLM_EXE")"
MISSING=""
for d in $DEPS; do
	lower="$(echo "$d" | tr 'A-Z' 'a-z')"
	case "$lower" in
		kernel32.dll|user32.dll|msvcrt.dll|advapi32.dll|shell32.dll|ole32.dll|gdi32.dll|shlwapi.dll|ws2_32.dll|imm32.dll|winmm.dll|comdlg32.dll|version.dll|gkrellm.exe)
			continue ;;
	esac
	if [ ! -f "$GKRELLM_DIR/$d" ]; then
		MISSING="$MISSING $d"
	fi
done

if [ -n "$MISSING" ]; then
	echo
	echo "  The plugin imports DLLs that are not present next to gkrellm.exe:"
	for d in $MISSING; do echo "      $d"; done
	echo
	echo "  Windows would refuse to load the plugin without any error message."
	die "unsatisfied runtime dependencies"
fi
ok "all runtime dependencies are satisfied by the GKrellM installation"

echo
echo "    Result: $OUT/gkrellm-gpu.dll"
